# docker-compose.yml
version: '3'
services:
  wog:
    build: .
    ports:
      - "8777:8777"
    volumes:
      - ./Scores.txt:/Scores.txt

# Jenkinsfile
pipeline {
    agent any
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('Build') {
            steps {
                sh 'docker build -t wog-app .'
            }
        }
        
        stage('Run') {
            steps {
                sh '''
                    docker run -d -p 8777:8777 -v $(pwd)/Scores.txt:/Scores.txt --name wog-test wog-app
                    sleep 5  # Wait for application to start
                '''
            }
        }
        
        stage('Test') {
            steps {
                sh 'python e2e.py'
            }
        }
        
        stage('Finalize') {
            steps {
                sh '''
                    docker stop wog-test
                    docker rm wog-test
                    docker tag wog-app $DOCKER_HUB_USERNAME/wog-app:latest
                    docker push $DOCKER_HUB_USERNAME/wog-app:latest
                '''
            }
        }
    }
}

# requirements.txt
flask==2.0.1
requests==2.26.0
selenium==4.1.0